# Site settings
title: 18FC Slides
email: vladlen.zvenyach@gsa.gov

description: > # this means to ignore newlines until "baseurl:"
  Slide decks for 18F [Consulting]!

baseurl: "/slides"
url: "https://18f.github.io"

# Build settings
markdown: kramdown
markdown_ext: ignoreme

collections:
    slides:
        output: true
        permalink: "/:path/"
