# Site settings
title: 18F Slides
email: vladlen.zvenyach@gsa.gov

description: > # this means to ignore newlines until "baseurl:"
  Slide decks for 18F and TTS!

baseurl: "/slides"
url: "https://slides.18f.gov"

# Build settings
markdown: redcarpet

collections:
  slides:
    output: true
    permalink: "/:path/"
